"""Generate structured decision memos from session results. No LLM calls — template-driven."""

from typing import Any


def generate_memo(session: dict[str, Any], memo_type: str) -> str:
    """Generate a formatted memo from session data.

    memo_type: 'research_brief' | 'risk_memo' | 'investment_memo'
    """
    generators = {
        "research_brief": _research_brief,
        "risk_memo": _risk_memo,
        "investment_memo": _investment_memo,
    }
    gen = generators.get(memo_type, _research_brief)
    return gen(session)


def _get(session: dict, *keys, default: str = "Not available") -> str:
    """Safely extract nested session fields."""
    obj = session
    for key in keys:
        if isinstance(obj, dict):
            obj = obj.get(key)
        else:
            return default
    return str(obj) if obj else default


def _format_claims(session: dict) -> str:
    """Format claim breakdown as a list."""
    claims = session.get("claim_breakdown", [])
    if not claims:
        return "No claim breakdown available."

    status_icons = {
        "supported": "[SUPPORTED]",
        "weakly_supported": "[WEAK]",
        "disputed": "[DISPUTED]",
        "insufficient_evidence": "[UNVERIFIED]",
    }

    lines = []
    for i, c in enumerate(claims, 1):
        icon = status_icons.get(c.get("status", ""), "[?]")
        line = f"{i}. {icon} {c.get('claim', 'N/A')}"
        if c.get("reasoning"):
            line += f"\n   Reasoning: {c['reasoning']}"
        if c.get("source_url"):
            line += f"\n   Source: {c['source_url']}"
        lines.append(line)

    return "\n\n".join(lines)


def _format_sources(session: dict) -> str:
    """Format web evidence as a source list."""
    evidence = session.get("web_evidence")
    if not evidence:
        return "No web sources available."

    lines = []
    for category in ("general", "counter", "statistical"):
        items = evidence.get(category, [])
        if items:
            lines.append(f"**{category.title()} Sources:**")
            for item in items[:3]:
                if isinstance(item, dict):
                    title = item.get("title", "Untitled")
                    url = item.get("url", "")
                    lines.append(f"  - {title}\n    {url}")
    return "\n".join(lines) if lines else "No web sources available."


def _format_dissent(session: dict) -> str:
    """Format dissenting views and conflicts."""
    parts = []
    vs = session.get("verdict_sections", {})
    if vs.get("dissenting_views"):
        parts.append(vs["dissenting_views"])
    if session.get("conflict_detected") and session.get("conflict_summary"):
        parts.append(f"Agent Conflict: {session['conflict_summary']}")
    return "\n\n".join(parts) if parts else "No significant dissent recorded."


def _research_brief(session: dict) -> str:
    query = session.get("query", "N/A")
    mode = session.get("analysis_mode", "default").replace("_", " ").title()
    score = session.get("hermes_score", "N/A")
    confidence = session.get("confidence_score", "N/A")
    verdict_label = _get(session, "verdict_sections", "verdict_label", default="N/A")
    arbiter = session.get("arbiter_verdict", "No verdict available.")
    vs = session.get("verdict_sections", {})

    # Truncate arbiter for executive summary
    summary = arbiter[:800] + "..." if len(arbiter) > 800 else arbiter

    return f"""# RESEARCH BRIEF
## Generated by HERMES Adversarial Intelligence Engine

---

**Query:** {query}
**Analysis Mode:** {mode}
**HERMES Score:** {score}/100
**Confidence:** {confidence}/100
**Verdict:** {verdict_label}
**Date:** {session.get('timestamp', 'N/A')[:10]}

---

## Executive Summary

{summary}

---

## Key Findings

{_format_claims(session)}

---

## Evidence Assessment

### Supporting Evidence
{vs.get('key_evidence_for', 'Not available')}

### Contradicting Evidence
{vs.get('key_evidence_against', 'Not available')}

### Missing Context
{vs.get('missing_context', 'Not identified')}

---

## Sources

{_format_sources(session)}

---

## Dissenting Views

{_format_dissent(session)}

---

## Open Questions

{vs.get('key_uncertainties', 'None identified')}

---

## Methodology

This brief was generated by a 5-agent adversarial council:
- **Advocate** (steel-manning) and **Skeptic** (Popperian falsification) provide opposing frames
- **Oracle** (base-rate empiricist) and **Contrarian** (Kuhnian paradigm challenger) add depth
- **Arbiter** (Bayesian synthesizer) delivers the final verdict
- Two rounds of deliberation ensure agents respond to each other's arguments
- Web evidence gathered from DuckDuckGo (general, counter, and statistical searches)

HERMES Score reflects adversarial confidence — how well the claim survives structured opposition.

---

*Generated by HERMES Ouroboros — hermes-ouroboros.online*
"""


def _risk_memo(session: dict) -> str:
    query = session.get("query", "N/A")
    score = session.get("hermes_score", "N/A")
    confidence = session.get("confidence_score", "N/A")
    verdict_label = _get(session, "verdict_sections", "verdict_label", default="N/A")
    vs = session.get("verdict_sections", {})
    arbiter = session.get("arbiter_verdict", "No verdict available.")

    survival = vs.get("survival_probability", "N/A")
    failure = vs.get("failure_probability", "N/A")

    return f"""# RISK MEMO
## Generated by HERMES Adversarial Intelligence Engine

---

**Subject:** {query}
**HERMES Score:** {score}/100
**Confidence:** {confidence}/100
**Verdict:** {verdict_label}
**Date:** {session.get('timestamp', 'N/A')[:10]}

---

## Thesis

{arbiter[:600]}{"..." if len(arbiter) > 600 else ""}

---

## Critical Risks

### Fatal Flaws
{vs.get('fatal_flaws', 'None identified by the adversarial council.')}

### Thinking Traps Detected
{vs.get('thinking_traps', 'None identified.')}

### Blind Spots
{vs.get('blind_spots', 'None identified.')}

---

## Survival Assessment

- **Survival Probability:** {survival}
- **Failure Probability:** {failure}

### Premortem (If This Fails, Here's Why)
{vs.get('premortem', 'Not available.')}

---

## Mitigants

### Key Strengths
{vs.get('key_strengths', 'Not identified.')}

### Fix or Die (Required Actions)
{vs.get('fix_or_die', 'None specified.')}

---

## Claim Analysis

{_format_claims(session)}

---

## Action Items

{vs.get('action_items', 'None specified.')}

---

## Evidence Base

{_format_sources(session)}

---

## Dissenting Views

{_format_dissent(session)}

---

## Decision Recommendation

Based on adversarial analysis with a HERMES Score of {score}/100:
{"PROCEED WITH CAUTION — significant risks identified but mitigable." if isinstance(score, int) and 40 <= score < 70 else "STRONG POSITION — risks are manageable and well-understood." if isinstance(score, int) and score >= 70 else "HIGH RISK — critical flaws or insufficient evidence. Further analysis recommended." if isinstance(score, int) and score < 40 else "Review the detailed analysis above for a nuanced assessment."}

---

*Generated by HERMES Ouroboros — hermes-ouroboros.online*
"""


def _investment_memo(session: dict) -> str:
    query = session.get("query", "N/A")
    score = session.get("hermes_score", "N/A")
    confidence = session.get("confidence_score", "N/A")
    verdict_label = _get(session, "verdict_sections", "verdict_label", default="N/A")
    vs = session.get("verdict_sections", {})
    arbiter = session.get("arbiter_verdict", "No verdict available.")

    return f"""# INVESTMENT MEMO
## Generated by HERMES Adversarial Intelligence Engine

---

**Subject:** {query}
**HERMES Score:** {score}/100
**Confidence:** {confidence}/100
**Verdict:** {verdict_label}
**Date:** {session.get('timestamp', 'N/A')[:10]}

---

## Thesis Summary

{arbiter[:600]}{"..." if len(arbiter) > 600 else ""}

---

## Bull Case

{vs.get('bull_case_summary', 'Not available from analysis.')}

### Supporting Evidence
{vs.get('key_evidence_for', 'Not available.')}

---

## Bear Case

{vs.get('bear_case_summary', 'Not available from analysis.')}

### Contradicting Evidence
{vs.get('key_evidence_against', 'Not available.')}

---

## Key Assumptions

{_format_claims(session)}

---

## Data Gaps

### Missing Context
{vs.get('missing_context', 'Not identified.')}

### Key Uncertainties
{vs.get('key_uncertainties', 'None identified.')}

### Source Credibility
{vs.get('source_credibility', 'Not assessed.')}

---

## Risk Assessment

### Fatal Flaws
{vs.get('fatal_flaws', 'None identified.')}

### Thinking Traps
{vs.get('thinking_traps', 'None identified.')}

### Blind Spots
{vs.get('blind_spots', 'None identified.')}

---

## Evidence Base

{_format_sources(session)}

---

## Dissenting Views

{_format_dissent(session)}

---

## Confidence-Weighted Conclusion

**HERMES Score: {score}/100** | **Confidence: {confidence}/100**

{"STRONG CONVICTION — The adversarial council found this thesis well-supported with manageable risks. Evidence quality is high." if isinstance(score, int) and score >= 70 else "MODERATE CONVICTION — The thesis has merit but significant uncertainties remain. Key assumptions need validation." if isinstance(score, int) and 40 <= score < 70 else "LOW CONVICTION — Critical gaps in evidence or significant counter-arguments. Not recommended without further due diligence." if isinstance(score, int) and score < 40 else "Review the detailed analysis above."}

---

*Generated by HERMES Ouroboros — hermes-ouroboros.online*
"""
